services:
  load_test:
    build: .
    image: load_test
    environment:
      # MUST use GMT time
      DESTINED_UNIX_TIME: 2024-11-26T01:30:00
      URL: http://test_server:8000/
    deploy:
      mode: replicated
      replicas: 1
