services:
  load_test:
    build: 
      context: .
      target: builder
    image: load_test
    # command: tail -f /dev/null 
    command: opam exec dune exec load_test
    environment:
      # MUST use PST time: 24 hour clock in format YYYY-MM-DDTHH:MM:SS
      SCHEDULED_TIME:
      REQUEST_NUMBER:
      URL:
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
