services:
  load_test:
    build: ./load_test
    image: load_test
    environment:
      DESTINED_UNIX_TIME: 1732569420
      URL: http://test_server:8000/
    deploy:
      mode: replicated
      replicas: 1
