services:
  load_test:
    build: 
      context: .
      target: builder
    image: load_test
    command: opam exec dune exec ./client_piaf.exe
    environment:
      # enable stack trace
      OCAMLRUNPARAM: b
      # MUST use PST time: 24 hour clock in format YYYY-MM-DDTHH:MM:SS
      SCHEDULED_TIME:
      REQUEST_NUMBER:
      URL:
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 2s
        condition: on-failure
  dev:
    build:
      context: .
      target: dev
    image: load_test-dev
    container_name: load_test-dev
    working_dir: /app
    command: tail -f /dev/null
