services:
  load_test:
    build: .
    image: load_test
    environment:
      DESTINED_UNIX_TIME: 1732569900
      URL: http://test_server:8000/
    deploy:
      mode: replicated
      replicas: 1
