services:
  load_test:
    build: .
    image: load_test
    environment:
      # MUST use GMT time
      SCHEDULED_TIME: 2024-11-26T01:40:00
      URL: http://lin-jchen-01.int.cpacket.com:8000/
    deploy:
      mode: replicated
      replicas: 100
