services:
  load_test:
    build: 
      context: .
      target: builder
    image: load_test
    # command: tail -f /dev/null 
    command: opam exec dune exec load_test
    environment:
      REQUEST_NUMBER: 1
      # MUST use GMT time
      SCHEDULED_TIME: 2024-11-26T01:40:00
      URL: http://lin-jchen-01.int.cpacket.com:8000/
    deploy:
      mode: replicated
      replicas: 1
