services:
  load_test:
    build: 
      context: .
      target: builder
    image: load_test
    # command: tail -f /dev/null 
    command: opam exec dune exec load_test
    env_file:
      - .env
    environment:
      REQUEST_NUMBER: 3
      URL: http://lin-jchen-01.int.cpacket.com:8000/
    deploy:
      mode: replicated
      replicas: 1
